"""add reasoning_content to messages

Revision ID: 1cbaba7b04b9
Revises: 68bbb0654a2d
Create Date: 2026-05-02 02:54:16.161114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cbaba7b04b9'
down_revision = '68bbb0654a2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reasoning_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'reasoning_content')
    # ### end Alembic commands ###
