"""add sessions and integration tables

Revision ID: 68bbb0654a2d
Revises: 004
Create Date: 2026-05-02 01:23:13.049559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68bbb0654a2d'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.alter_column('ai_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('ai_configs', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('ai_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('ai_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_ai_configs_is_default', table_name='ai_configs')
    op.drop_index('ix_ai_configs_provider', table_name='ai_configs')
    op.create_index(op.f('ix_ai_configs_id'), 'ai_configs', ['id'], unique=False)
    op.alter_column('orders', 'split_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('orders', 'is_split',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint('fk_orders_parent_order_id', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'orders', ['parent_order_id'], ['id'])
    op.alter_column('task_dependencies', 'dependency_type',
               existing_type=postgresql.ENUM('finish_to_start', 'start_to_start', 'finish_to_finish', 'start_to_finish', name='dependencytype'),
               nullable=True)
    op.alter_column('task_dependencies', 'lag_time',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('ix_task_dependencies_predecessor_id', table_name='task_dependencies')
    op.drop_index('ix_task_dependencies_successor_id', table_name='task_dependencies')
    op.create_index(op.f('ix_task_dependencies_id'), 'task_dependencies', ['id'], unique=False)
    op.drop_constraint('task_dependencies_predecessor_id_fkey', 'task_dependencies', type_='foreignkey')
    op.drop_constraint('task_dependencies_successor_id_fkey', 'task_dependencies', type_='foreignkey')
    op.create_foreign_key(None, 'task_dependencies', 'schedules', ['predecessor_id'], ['id'])
    op.create_foreign_key(None, 'task_dependencies', 'schedules', ['successor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_dependencies', type_='foreignkey')
    op.drop_constraint(None, 'task_dependencies', type_='foreignkey')
    op.create_foreign_key('task_dependencies_successor_id_fkey', 'task_dependencies', 'schedules', ['successor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('task_dependencies_predecessor_id_fkey', 'task_dependencies', 'schedules', ['predecessor_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_task_dependencies_id'), table_name='task_dependencies')
    op.create_index('ix_task_dependencies_successor_id', 'task_dependencies', ['successor_id'], unique=False)
    op.create_index('ix_task_dependencies_predecessor_id', 'task_dependencies', ['predecessor_id'], unique=False)
    op.alter_column('task_dependencies', 'lag_time',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('task_dependencies', 'dependency_type',
               existing_type=postgresql.ENUM('finish_to_start', 'start_to_start', 'finish_to_finish', 'start_to_finish', name='dependencytype'),
               nullable=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('fk_orders_parent_order_id', 'orders', 'orders', ['parent_order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('orders', 'is_split',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('orders', 'split_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_ai_configs_id'), table_name='ai_configs')
    op.create_index('ix_ai_configs_provider', 'ai_configs', ['provider'], unique=False)
    op.create_index('ix_ai_configs_is_default', 'ai_configs', ['is_default'], unique=False)
    op.alter_column('ai_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('ai_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('ai_configs', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('ai_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
